/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.SwingUtilities;

/**
 *
 * @author wallace.amorim
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final ScheduledExecutorService background = Executors.newSingleThreadScheduledExecutor();
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        LocalDate localDate = LocalDate.now();
        Date date = Date.from(Instant.now());
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String data = format.format(date);
        
        LData.setText(data);
        
        long delayInicial = 0;
        long intervaloDeInvocacao = 1;
        TimeUnit segundos = TimeUnit.SECONDS;
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm:ss");
        Runnable tarefa = () -> SwingUtilities.invokeLater(
            () -> lhora.setText(LocalTime.now().format(formatter))
        );
        background.scheduleAtFixedRate(tarefa, delayInicial, intervaloDeInvocacao, segundos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LData = new javax.swing.JLabel();
        lhora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_CadastroP = new javax.swing.JMenu();
        JM_CadastroP_Clientes = new javax.swing.JMenuItem();
        JM_CadastroP_Funcionarios = new javax.swing.JMenuItem();
        JM_CadastroP_Cidades = new javax.swing.JMenuItem();
        JM_CadastroP_Bairro = new javax.swing.JMenuItem();
        JM_CadastroP_Cargo = new javax.swing.JMenuItem();
        JM_CadastroP_Fornecedores = new javax.swing.JMenuItem();
        JM_CadastroP_Sair = new javax.swing.JMenuItem();
        JM_Consultas = new javax.swing.JMenu();
        JM_Relatorio = new javax.swing.JMenu();
        JM_Utilitarios = new javax.swing.JMenu();
        JM_Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LData.setText("Data:");

        lhora.setText("hora:");

        JM_CadastroP.setText("Cadastros");

        JM_CadastroP_Clientes.setText("Clientes");
        JM_CadastroP.add(JM_CadastroP_Clientes);

        JM_CadastroP_Funcionarios.setText("Funcionários");
        JM_CadastroP.add(JM_CadastroP_Funcionarios);

        JM_CadastroP_Cidades.setText("Cidades");
        JM_CadastroP.add(JM_CadastroP_Cidades);

        JM_CadastroP_Bairro.setText("Bairro");
        JM_CadastroP.add(JM_CadastroP_Bairro);

        JM_CadastroP_Cargo.setText("Cargo");
        JM_CadastroP.add(JM_CadastroP_Cargo);

        JM_CadastroP_Fornecedores.setText("Fornecedores");
        JM_CadastroP.add(JM_CadastroP_Fornecedores);

        JM_CadastroP_Sair.setText("Sair");
        JM_CadastroP.add(JM_CadastroP_Sair);

        jMenuBar1.add(JM_CadastroP);

        JM_Consultas.setText("Consultas");
        jMenuBar1.add(JM_Consultas);

        JM_Relatorio.setText("Relatórios");
        jMenuBar1.add(JM_Relatorio);

        JM_Utilitarios.setText("Utilitarios");
        jMenuBar1.add(JM_Utilitarios);

        JM_Sair.setText("Sair");
        jMenuBar1.add(JM_Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(LData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lhora)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LData)
                    .addComponent(lhora))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JM_CadastroP;
    private javax.swing.JMenuItem JM_CadastroP_Bairro;
    private javax.swing.JMenuItem JM_CadastroP_Cargo;
    private javax.swing.JMenuItem JM_CadastroP_Cidades;
    private javax.swing.JMenuItem JM_CadastroP_Clientes;
    private javax.swing.JMenuItem JM_CadastroP_Fornecedores;
    private javax.swing.JMenuItem JM_CadastroP_Funcionarios;
    private javax.swing.JMenuItem JM_CadastroP_Sair;
    private javax.swing.JMenu JM_Consultas;
    private javax.swing.JMenu JM_Relatorio;
    private javax.swing.JMenu JM_Sair;
    private javax.swing.JMenu JM_Utilitarios;
    private javax.swing.JLabel LData;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lhora;
    // End of variables declaration//GEN-END:variables
}
